export class CoffeeConstants {
  static readonly PRIMARY_COLOR = '#5B3A1F';
  static readonly ACCENT_COLOR = '#C6A575';
  static readonly WHITE = '#FFFFFF';
  static readonly TEXT_COLOR = '#C6A575';

  // Step type colors
  static readonly ESPRESSO_COLOR = '#3E2723';
  static readonly MILK_COLOR = '#FFF9C4';
  static readonly WATER_COLOR = '#E1F5FE';

  static readonly WATCH_SIZE = '466px';

  static readonly PREFERENCES_NAME = 'BaristaPreferences';
  static readonly KEY_FAVORITES = 'favorites';
  static readonly KEY_HISTORY = 'history';
}
